### ISSUE TITLE
RunTimeError - alignData

### ISSUE THREAD

**Issue by basakakdogan** [ChristophKirst/ClearMap#18]
I get the following error when I try to run alignData. Do you have any suggestions?

Thanks.

resultDirectory  = alignData(**RegistrationAlignmentParameter);
Traceback (most recent call last):

  File "<ipython-input-116-4b734736d595>", line 1, in <module>
    resultDirectory  = alignData(**RegistrationAlignmentParameter);

  File "ClearMap/Alignment/Elastix.py", line 466, in alignData
    raise RuntimeError('alignData: failed executing: ' + cmd);

RuntimeError: alignData: failed executing: /home/kandellabalien/ClearMap/ClearMap/Elastix/bin/elastix -threads 16 -m /home/kandellabalien/ClearMap/ClearMap/clearmap_ressources_mouse_brain/ClearMap_ressources/25umAutofluoReference/template_25_half.tif -f /home/kandellabalien/ClearMap/Eleanortesthemifromimage450/autofluo_resampled.tif -p /home/kandellabalien/ClearMap/ClearMap/clearmap_ressources_mouse_brain/ClearMap_ressources/Parameter_files/Par0000affine.txt -p /home/kandellabalien/ClearMap/ClearMap/clearmap_ressources_mouse_brain/ClearMap_ressources/Parameter_files/Par0000bspline.txt -out /home/kandellabalien/ClearMap/Eleanortesthemifromimage450/elastix_auto_to_atlas

**Comment by keithmurphy** [comment]
Did you happen to find a solution to this problem? I saw the other issues thread had issue with using spaces but my directories have only _ and I'm still getting that problem. I'd love any advice you might have.
