### ISSUE TITLE
iDISCO Python Module

### ISSUE THREAD

**Issue by pforai** [ChristophKirst/ClearMap#2]
Hi guys!

I'm tripping over a non existing iDISCO python module that needs to be imported in one of the files of the test suite. Can't find anything python related to iDISCO. Any hints? I'm running master:
```python
>>> print ClearMap.__version__
0.9.2
```

**Comment by ChristophKirst** [comment]
Hi, 

can you specify this more concretely? What command & routines do you use to get the error message?

C.

**Comment by pforai** [comment]
I was trying to run the test suite within the repo here.

**Comment by ChristophKirst** [comment]
You are right, some of the test routines in the Test directory are not updated to the new name ClearMap naming, i look into this and/or will simply remove some of the older outdated test code.
It should not affect the main functionality of the program at all.
Most modules have their own test code under the test() routine which should work.

**Comment by pforai** [comment]
The test functions import from the iDISCO namespace as well. It's not a problem per se, but it would have been fine to check if our install is doing fine or if we screwed up somewhere.

**Comment by ChristophKirst** [comment]
Good to know, thanks for pointing it out !
At some point we changed the software name from iDISCO to ClearMap to separate the experimental protocol from the software that in principle could be used with a different clearing technique etc. 
I probably forgot to clean up / update some of the test routines and the Test folder after the name change. I will do in the next few days, the code should run though independent of this though.
